### PR TITLE
fnc rtsp: support basic and digest auth

### PR DESCRIPTION
**Pull request by jasaw**
Back end support of optional basic and digest authentication mode in Fast Network Camera mode. This PR does **not** cover the web interface implementation.

**Digest Auth**
To enable digest auth, set the below fields in `/data/etc/streameye.conf` file:
```
AUTH="digest"
CREDENTIALS="username:password:motionEyeOS"
```

**Basic Auth**
To enable basic auth, set the below fields in `/data/etc/streameye.conf` file:
```
AUTH="basic"
CREDENTIALS="username:password:motionEyeOS"
```

Note that basic auth is highly insecure, so the web interface should default to digest auth if auth is enabled.

### CODE REVIEW

**Comment by ccrisan** [comment]
@jasaw this looks good to me. We'll have to add support for this in the UI. But I don't see any harm in having this merged without UI for now. What do you think?

**Review by ccrisan — APPROVED** [review]

**Comment by jasaw** [comment]
@ccrisan Sorry, don't merge this just yet. I'm looking into adding auth realm and rebase to latest dev branch with RPi4 support too. I'll keep you updated.

**Comment by ccrisan** [comment]
Got it. Keep me posted and keep up the good work :)

**Comment by jasaw** [comment]
Auth realm requires GStreamer 1.16, which requires ffmpeg version 4. I've just upgraded and compiled my gstreamer and ffmpeg, going to spend some time to test it. @popoviciri mentioned gstreamer 1.16 has high latency, so I'm going to check that as well.

**Comment by jasaw** [comment]
@ccrisan I've upgraded ffmpeg and gstreamer packages and done some basic testing. I can't tell any performance difference between the new and the old versions. I'm getting 2.5 seconds RTSP latency on my test Raspberry Pis (via Ethernet).

I haven't tried compiling for the other platforms with new ffmpeg and gstreamer.

The real question is, should we be upgrading ffmpeg and gstreamer? Thoughts?

**Comment by jasaw** [comment]
@ccrisan I think it's better to keep the current version of ffmpeg and gstreamer for now. The new version seems to have accumulating latency. Latency on my test unit has gone up to 20 seconds. Auth realm support is still in this PR, but will be ignored for now.

**Pull request closed without merging**
