### PR TITLE
motion: Fix bitrate

### PR DESCRIPTION
**Pull request by jasaw**
Here's the PR that hopefully fixes bad quality video recording. https://github.com/ccrisan/motioneyeos/issues/1900

I don't have enough evidence to prove that it does fix the issue, but we need more users to test this, so maybe it's best to merge it in so users can start testing.

We'll have to remove this patch when it's merged into upstream motion.

### CODE REVIEW

**Comment by ccrisan** [comment]
Looks good. What did the Motion devs say about this? Can't we have this merged upstream and rely on one of their latest commits?

**Comment by jasaw** [comment]
I didn't get any feedback from motion dev for a few reasons.
- Motion devs rely on us to test anything related to OMX before merging. 
- Dave, who is the main motion dev, only works on motion in Q4 every year, September onwards.

**Comment by Mr-DaveDev** [comment]
FYI, OMX is still blacklisted in Motion due to lock ups with non modified ffmpeg releases.  (I haven't heard/seen that the upstream issue has been resolved.)  

This revision will go into Motion, it just may be a while.

**Comment by ccrisan** [comment]
Alright, fair enough. Then let's have this as a patch to Motion in the OS for now.

**Review by ccrisan — APPROVED** [review]

**Comment by jasaw** [comment]
@ccrisan This has been merged upstream. We'll need to revert this patch when next time we upgrade motion.

**Pull request merged**
