### PR TITLE
ffmpeg: force-disable zerocopy for RPi OMX patch

### LINKED ISSUE #2523: ghostimages/artefacts on recordings
### motionEyeOS Version

I am running motionEyeOS version: dev20200907

### Board Model

I am using the following board/model: Raspberry Pi 3B

### Camera

I am using the following type of camera: V4L2 and Simple MJPEG Camera

Microsoft_Microsoft®_LifeCam_HD-3000
Dlink DCS 930L

### Network Connection

My motionEyeOS unit is connected to the network via: Ethernet

### Peripherals

I am using the following peripherals that I consider relevant to this issue:

 * External USB Hard Disk

### Log Files

I consider the following log files relevant to this issue:

[boot.log](https://github.com/ccrisan/motioneyeos/files/5252437/boot.log)
[motioneye.log](https://github.com/ccrisan/motioneyeos/files/5252438/motioneye.log)

I have weird artefacts since 2 days (not sure if it was since the update to the dev-version): both cams got ghost-images of certain image-elements that appear shifted to the left and in some pinkish color. The USB-Camera also has a bright green line at the top of the image. It's not a camera-fault, both cameras work normally. Also the livestream in the webinterface is working correctly but I get those artefacts in all recordings. I use the motion-triggered mode.

### PR DESCRIPTION
**Pull request by nmschulte**
Resolves #2523 and likely #2542.

### CODE REVIEW

**Comment by ccrisan** [comment]
Thanks! @jasaw do you think this should be enough for us to use the latest ffmpeg with OMX?

**Comment by JohanD78** [comment]
OMX works fine with no artifacts with the dev201025 release. Verified on both Pi3 and Pi4

**Comment by jasaw** [comment]
It is very interesting that we still need to patch ffmpeg to disable zerocopy because motion already disables zerocopy here: https://github.com/Motion-Project/motion/blob/0faf44fefb4126722c44020269a7593994c97102/src/ffmpeg.c#L846
Something else must be broken in ffmpeg if disabling zerocopy via `av_dict_set` doesn't work. :-(

**Comment by nmschulte** [comment]
I'm not sure the issue is caused by this commit, but with my build, my RPi3 video seems to freeze/break.  It did not do this with the same/similar configuration on `20200606` build.  Rebooting seems to resolve the issue, but motion detection etc. seems to not work when it's in this frozen/broken state.

**Comment by PhinPhin** [comment]
with the latest build I seem to got rid of the artefacts, but I now have broken videofiles every now and then, I can download the files but neither I can play it nor can MotionEyeOS create thumbnails: 

image

Very annoying, since I use motion-detection to start recording and the motion-events are kind of important. Is there another issue that would explain this?

**Pull request merged**
