### PR TITLE
Update ffmpeg to 4.3.1

### PR DESCRIPTION
**Pull request by popoviciri**
I've been experiencing troubles with ffmpeg 4.2.3 version from latest stable buildroot:
- crash followed by reboot during thumbnail previews.
- mjpeg stream would not preview or pass the frames to motion; this is needed for use with multi_stream_mmal and rtsp pass-through in motion.

I tried many thing such as upgrading motion and motioneye to latest master. In the end this update to ffmpeg got my rpi3 back to life. I am aware that the situation might be particular to my case but the update works nonetheless.
Cheers!

### CODE REVIEW

**Comment by ccrisan** [comment]
@popoviciri thanks for your PR. I chose to cherry-pick the corresponding commits from BuildRoot (and merged them into thingOS) rather than using your separate commits. The result should be identical; i chose cherry-picking to prevent conflicts when merging in future BuildRoot versions.

**Comment by ccrisan** [comment]
Closed in favor of 3b9c66fd02f8f6d24f82febd94da71d6ece1df9e.

**Comment by popoviciri** [comment]
That's perfect. Thanks for upgrading!

**Comment by popoviciri** [comment]
By the way: remember to remove the two patches:
- 1003-avcodec-v4l2-enable-bit-rate-control-for-mfc-encoder.patch
- 1007-v4l2-buffers-add-handling-for-NV21-and-YUV420P.patch

As far as I can tell they're both accounted for upstream.
Also, ffmpeg will not compile with them :).
Cheers!

**Comment by ccrisan** [comment]
Auch, you're right. Thanks for the tip.

**Pull request closed without merging**
