### PR TITLE
Motion: Drain codec

### PR DESCRIPTION
**Pull request by jasaw**
This pull-request fixes a few things:
- Set frame PTS before encoding.
- Decouple avcodec send and receive.
- Drain codec at the end of an encoding session.
- Replace alloca with malloc.

This fixes apply to all platforms, not just the RPi.

I have done minimal testing, but created this PR as requested by @ccrisan .

### CODE REVIEW

**Comment by ccrisan** [comment]
@jasaw I'm thinking of having this merged directly into dev, so that it can make its way towards the next release. Given your experience with motion, which of the following options do you think would be the best (or applicable, at all):
1. Update motion to the latest commit on master (as opposed to the stable 4.0.1 version which is used right now).
2. Apply this patch to the stable 4.0.1 source code.

Personally, I would go with the 1st one as I have seen many many fixes merged into motion during the past few months and it would be a pity not to benefit of them asap. Do you think the current motion master source tree is "stable" enough?

**Comment by jasaw** [comment]
@ccrisan I fully agree with you that we should move to the latest master. My reasons are:
- A lot of bugs have been fixed in master. Given that the "stable" 4.0.1 has a lot of issues to begin with, I would expect latest master to perform better, less bugs and more stable. What's your experience with the motion master stability?
- Latest master will be easier to maintain because we can hotfix an issue, and submit the same patch to motion upstream. The latest master code has changed a lot since version 4.0.1, it'll be more work to manually apply hotfix/patches back and forth between upstream and motionEyeOS.

**Comment by ccrisan** [comment]
My experience with motion's master was always good (at least, always better than the stable one). I'll move forward with updating motion to latest master commit.

**Comment by jasaw** [comment]
@ccrisan Some of my motion patches have been merged upstream. One of the patches that has been merged is to allow preferred codec in motion config, but still requires `enable-h264-omx-codec.patch` to remove h264_omx codec from the blacklist. This `enable-h264-omx-codec.patch` should be applied against rpi-omx branch. All the other patches can be applied to dev if you want.

**Comment by ccrisan** [comment]
Alrighty then. I have just updated motion in the dev branch. It's now the latest commit - not tested though. What patches do we still need to apply against the current dev for this PR?

**Comment by jasaw** [comment]
@ccrisan What's your plan on rpi-omx and dev branches? I know rpi-omx branch is where we test the h264_omx work. Is dev branch supposed to include h264_omx work too?

The reason for asking is this:
This drain codec PR was originally created against the rpi-omx branch, so it includes h264_omx work. By changing the base branch, we are applying both the h264_omx and drain codec work against dev branch. Is this your intention?

Another note:
Which motionEye commit are we supposed to use for this PR?

**Comment by ccrisan** [comment]
@jasaw first off, I apologize for my relatively large response time. Projects and tasks have started to pile up both at work and at home and I have very very little time to work on motionEyeOS these days. Anyways, the plan is as follows:

 * we do a **stable release** from the current **master** as soon as we get #1116 solved (it's a horrible bug that I simply can't reproduce)
 * soon after that I plan to merge #1123 (or at least what I think it does) into **dev** and have a **prerelease**.

If you think the **rpi-omx** branch together with the drain codec PR (and possibly the MMAL PR #1088) is not too much (in terms of possible bugs) for one release, we could do that.

Given the mainline motion support for codec selection that we have now, we can safely merge motionEye's rpi-omx into dev and use that from now on.

**Comment by jasaw** [comment]
@ccrisan No worries, I completely understand.

I think it's low risk to get **drain codec + rpi-omx + motionEye's rpi-omx** into dev branch, do a pre-release, and start getting people to test it. We can't possibly do a "good enough" test coverage given our lack of free time and hardware. If users are having problem with h264_omx codec, they can simply choose the good old libx264 codec from the web UI.

Regarding MMAL #1088, there's no point getting it into dev unless motionEye supports it. I would leave it out until we get a stable release with rpi-omx.

**Comment by ccrisan** [comment]
Alright, then we have a plan.

**Comment by jasaw** [comment]
@ccrisan I think what we have now is looking promising.
- #1116 appears to be caused by old browser cache from 2 of the users who reported the problem.
- drain codec + rpi-omx + motionEye's rpi-omx appears to work well for those users who had video recording problem.

**Comment by ccrisan** [comment]
I know it's been ages since you opened this PR :) Anyways I've finally managed to put together everything for the next stable release (using the master branch with some git cherry-picking). So I could finally merge this PR into dev.

I have also merged the motionEye rpi-omx branch and updated the motionEye package as well. Motion is also up-to-date with current master. I believe we could start testing and building for a next prerelease.

So given the current motionEyeOS dev branch:
 * is there anything else you think we should merge in or update?
 * all current motion patches are still required?
 * latest ffmpeg version as of today is 3.3.4; should we also update it?

**Comment by jasaw** [comment]
@ccrisan Nice. I've checked the dev branch, looks good. I'm still compiling it, but don't expect to have any problem here.

To answer your questions:
- I can't think of anything else we should be merging into this pre-release.
- All the motion patches are still required. There hasn't been any activity in upstream motion, so my patches are still waiting to be merged.
- It's always hard to decide whether to update a package or not. I have been testing with 3.3.4 for a few months now, haven't had any issues with it. I would probably update it.

**Comment by ccrisan** [comment]
@jasaw 20171003 stable release is finally out (let's hope it is stable indeed, as I'm still not convinced #1116 was caused by the browser's cache). Anyways, I've updated ffmpeg and merged in other minor unrelated stuff.

I think the next step now would be to compile the current dev and put out a new prerelease with what Is basically all of your work. What do you think?

**Comment by jasaw** [comment]
@ccrisan Sounds great ! Let's get the dev prerelease out so more people can start testing it.

**Comment by ccrisan** [comment]
@jasaw the current dev does not compile on arm64 boards (Odroid C2, Pine64 and Odroid XU4). More precisely, ffmpeg has some undefined refs:

    GEN     libavcodec/libavcodec.ver
    LD      libavcodec/libavcodec.so.57
    LD      libavformat/libavformat.so.57
    LD      libavfilter/libavfilter.so.6
    LD      libavdevice/libavdevice.so.57
    LD      ffmpeg_g
    libavcodec/libavcodec.so: undefined reference to `ff_vp9_copy64_aarch64'
    libavcodec/libavcodec.so: undefined reference to `ff_idctdsp_init_aarch64'
    libavcodec/libavcodec.so: undefined reference to `ff_vp9_copy128_aarch64'
    libavcodec/libavcodec.so: undefined reference to `ff_vp9_copy32_aarch64'
    collect2: error: ld returned 1 exit status
    Makefile:136: recipe for target 'ffmpeg_g' failed
    make[2]: *** [ffmpeg_g] Error 1
    package/pkg-generic.mk:216: recipe for target '/opt/buildroot/motioneyeos/output/pine64/build/ffmpeg-3.3.4/.stamp_built' failed
    make[1]: *** [/opt/buildroot/motioneyeos/output/pine64/build/ffmpeg-3.3.4/.stamp_built] Error 2
    Makefile:79: recipe for target '_all' failed
    make: *** [_all] Error 2

Any idea how we could fix this?

**Comment by jasaw** [comment]
@ccrisan I've never tested with 64-bit architecture because I don't have hardware here. Looks like something's broken going from ffmpeg version 3.2.3 to 3.3.2. It has something to do with Neon and Arch64. All the errors are related to neon optimisations that are only available if compiling for 32-bit architectures.

Let's revert back to ffmpeg version 3.2.3 and wait for buildroot developers to fix it.

**Comment by ccrisan** [comment]
@jasaw I got it working with the latest [ffmpeg.mk](https://git.busybox.net/buildroot/tree/package/ffmpeg/ffmpeg.mk) file from BuildRoot + all of your RPi-OMX related stuff. I have yet to test that whatever comes out of this still works, but at least it compiles just fine.

**Comment by ccrisan** [comment]
@jasaw one more thing: looking through the current BuildRoot's ffmpeg.mk I see the following lines:

```
ifeq ($(BR2_PACKAGE_RPI_FIRMWARE)$(BR2_PACKAGE_RPI_USERLAND),yy)
FFMPEG_CONF_OPTS += --enable-mmal --enable-omx --enable-omx-rpi \
	--extra-cflags=-I$(STAGING_DIR)/usr/include/IL
FFMPEG_DEPENDENCIES += rpi-firmware rpi-userland
else
FFMPEG_CONF_OPTS += --disable-mmal --disable-omx --disable-omx-rpi
endif
```

As far as I can tell, they do almost the same thing as your change to ffmpeg, except that they deduce the presence of the rpi firmware/userland packages directly. Do you confirm it's safe to use their version directly, getting rid of `BR2_PACKAGE_FFMPEG_RPI_HW_CODECS`?

**Comment by jasaw** [comment]
Yes, it's safe to use their version. It makes maintenance easier on the future too.

**Comment by ccrisan** [comment]
@jasaw I have prepared a draft release called 20171008 with builds from the current dev. It contains all of your work and from my personal tests on RPi1 and RPi3 boards, I can say that the h264 + OMX hardware encoding is amazing. The performance gains are considerable.

Will you please also run some tests and make sure that everything is in place and works as expected before I publish the prerelease?

P.S. given your rights to motionEyeOS, you should be able to see the *unreleased* draft and download the compiled images. If that's not the case, please let me know.

**Comment by jasaw** [comment]
@ccrisan Yes, I can see your draft release. I'll test the images later today.

**Comment by jasaw** [comment]
@ccrisan I have just tested the draft release on my various models of raspberry pis. Works great ! Nice work getting it into a release. :-)

**Comment by ccrisan** [comment]
@jasaw the draft has been (pre)released. Please take a look over the release notes and let me know if there's anything missing or if there's something you might add/change. Heck, you can modify it yourself.

**Comment by jasaw** [comment]
@ccrisan Is motioneyeos-raspberrypi3-20171004.img.gz file on the release a mistake? All the other files are *-20171008.

**Comment by ccrisan** [comment]
@jasaw it's there by mistake (it was in the folder when I uploaded them). It's removed now.

**Comment by ccrisan** [comment]
@jasaw some patches (e.g. [https://github.com/ccrisan/motioneyeos/blob/dev/package/motion/0011-do-not-force-keyframe.patch](0011-do-not-force-keyframe.patch)) can no longer be applied against recent motion master. Do they need to be updated? Are they still needed? Or did we remove them and they got back by accident?

**Comment by jasaw** [comment]
@ccrisan Ya, sorry, I forgot to update you on this one. This patch has been merged upstream, so no longer needed here.

If you use the latest master (git ec9a5f993dbc131b58142515ededbd090c497049) You can also get rid of `0012-decouple-avcodec-send-receive.patch` and `0013-drain-codec.patch`. Mr-Dave decided to implement his own drain codec function based on ours, but deferred the decouple patch because of some concerns. I haven't got time to test Mr-Dave's implementation, so I don't know whether it works or not.

**Comment by ccrisan** [comment]
@jasaw got it. Thanks.

**Pull request merged**
